import csv
import os

import pandas as pd
import pandss as pdss
import yaml

a_list = [
    ["SWP_TA_ACFC", "Alameda County FC&WCD, Zone 7", "Delivery - TA"],
    ["SWP_TA_ACWD", "Alameda County WD", "Delivery - TA"],
    ["SWP_TA_AVEK", "Antelope Valley-East Kern WA", "Delivery - TA"],
    ["SWP_TA_CLWA1", "Santa Clarita WA (San Joaquin)", "Delivery - TA"],
    ["SWP_TA_CLWA2", "Santa Clarita WA (South Coast)", "Delivery - TA"],
    ["SWP_TA_CVWD", "Coachella Valley WD", "Delivery - TA"],
    ["SWP_TA_KINGS", "County of Kings", "Delivery - TA"],
    ["SWP_TA_CLA", "Crestline-Line Arrowhead WA", "Delivery - TA"],
    ["SWP_TA_DESERT", "Desert WA", "Delivery - TA"],
    ["SWP_TA_DUDLEY", "Dudley Ridge WD", "Delivery - TA"],
    ["SWP_TA_EMPIRE", "Empire West Side ID", "Delivery - TA"],
    ["SWP_TA_KERNAG", "Kern County WA (Ag)", "Delivery - TA"],
    ["SWP_TA_KERNMI", "Kern County WA (MI)", "Delivery - TA"],
    ["SWP_TA_LCID", "Littlerock Creek ID", "Delivery - TA"],
    ["SWP_TA_MWD", "Metropolitan WDSC", "Delivery - TA"],
    ["SWP_TA_MWA", "Mojave WA", "Delivery - TA"],
    ["SWP_TA_NAPA", "Napa County FC&WCD", "Delivery - TA"],
    ["SWP_TA_OAK", "Oak Flat WD", "Delivery - TA"],
    ["SWP_TA_PWD", "Palmdale WD", "Delivery - TA"],
    ["SWP_TA_SBV", "San Bernadino Valley MWD", "Delivery - TA"],
    ["SWP_TA_SGV", "San Gabriel Valley MWD", "Delivery - TA"],
    ["SWP_TA_SGP", "San Gorgonio Pass WA", "Delivery - TA"],
    ["SWP_TA_SLO", "San Luis Obispo County FC&WCD", "Delivery - TA"],
    ["SWP_TA_SB", "Santa Barbara County FC&WCD", "Delivery - TA"],
    ["SWP_TA_SCV", "Santa Clara Valley WD", "Delivery - TA"],
    ["SWP_TA_SOLANO", "Solano County WA", "Delivery - TA"],
    ["SWP_TA_TULARE", "Tulare Lake Basin WSD", "Delivery - TA"],
    ["SWP_TA_VC", "Ventura County FCD", "Delivery - TA"],
    ["SWP_CO_ACFC", "Alameda County FC&WCD, Zone 7", "Delivery - CO"],
    ["SWP_CO_ACWD", "Alameda County WD", "Delivery - CO"],
    ["SWP_CO_AVEK", "Antelope Valley-East Kern WA", "Delivery - CO"],
    ["SWP_CO_CLWA2", "Santa Clarita WA (South Coast)", "Delivery - CO"],
    ["SWP_CO_CVWD", "Coachella Valley WD", "Delivery - CO"],
    ["SWP_CO_KINGS", "County of Kings", "Delivery - CO"],
    ["SWP_CO_CLA", "Crestline-Line Arrowhead WA", "Delivery - CO"],
    ["SWP_CO_DESERT", "Desert WA", "Delivery - CO"],
    ["SWP_CO_DUDLEY", "Dudley Ridge WD", "Delivery - CO"],
    ["SWP_CO_EMPIRE", "Empire West Side ID", "Delivery - CO"],
    ["SWP_CO_KERN", "Kern Counta WA", "Delivery - CO"],
    ["SWP_CO_LCID", "Littlerock Creek ID", "Delivery - CO"],
    ["SWP_CO_MWD", "Metropolitan WDSC", "Delivery - CO"],
    ["SWP_CO_MWA", "Mojave WA", "Delivery - CO"],
    ["SWP_CO_NAPA", "Napa County FC&WCD", "Delivery - CO"],
    ["SWP_CO_OAK", "Oak Flat WD", "Delivery - CO"],
    ["SWP_CO_PWD", "Palmdale WD", "Delivery - CO"],
    ["SWP_CO_SBV", "San Bernadino Valley MWD", "Delivery - CO"],
    ["SWP_CO_SGV", "San Gabriel Valley MWD", "Delivery - CO"],
    ["SWP_CO_SGP", "San Gorgonio Pass WA", "Delivery - CO"],
    ["SWP_CO_SLO", "San Luis Obispo County FC&WCD", "Delivery - CO"],
    ["SWP_CO_SB", "Santa Barbara County FC&WCD", "Delivery - CO"],
    ["SWP_CO_SCV", "Santa Clara Valley WD", "Delivery - CO"],
    ["SWP_CO_SOLANO", "Solano County WA", "Delivery - CO"],
    ["SWP_CO_TULARE", "Tulare Lake Basin WSD", "Delivery - CO"],
    ["SWP_CO_VC", "Ventura County FCD", "Delivery - CO"],
    ["SWP_CO_CLWA1", "Santa Clarita WA (San Joaquin)", "Delivery - CO"],
    ["SWP_IN_ACFC", "Alameda County FC&WCD, Zone 7", "Delivery - IN"],
    ["SWP_IN_ACWD", "Alameda County WD", "Delivery - IN"],
    ["SWP_IN_AVEK", "Antelope Valley-East Kern WA", "Delivery - IN"],
    ["SWP_IN_CLWA2", "Santa Clarita WA (South Coast)", "Delivery - IN"],
    ["SWP_IN_CVWD", "Coachella Valley WD", "Delivery - IN"],
    ["SWP_IN_KINGS", "County of Kings", "Delivery - IN"],
    ["SWP_IN_CLA", "Crestline-Line Arrowhead WA", "Delivery - IN"],
    ["SWP_IN_DESERT", "Desert WA", "Delivery - IN"],
    ["SWP_IN_DUDLEY", "Dudley Ridge WD", "Delivery - IN"],
    ["SWP_IN_EMPIRE", "Empire West Side ID", "Delivery - IN"],
    ["SWP_IN_KERN", "Kern Counta WA", "Delivery - IN"],
    ["SWP_IN_LCID", "Littlerock Creek ID", "Delivery - IN"],
    ["SWP_IN_MWD", "Metropolitan WDSC", "Delivery - IN"],
    ["SWP_IN_MWA", "Mojave WA", "Delivery - IN"],
    ["SWP_IN_NAPA", "Napa County FC&WCD", "Delivery - IN"],
    ["SWP_IN_OAK", "Oak Flat WD", "Delivery - IN"],
    ["SWP_IN_PWD", "Palmdale WD", "Delivery - IN"],
    ["SWP_IN_SBV", "San Bernadino Valley MWD", "Delivery - IN"],
    ["SWP_IN_SGV", "San Gabriel Valley MWD", "Delivery - IN"],
    ["SWP_IN_SGP", "San Gorgonio Pass WA", "Delivery - IN"],
    ["SWP_IN_SLO", "San Luis Obispo County FC&WCD", "Delivery - IN"],
    ["SWP_IN_SB", "Santa Barbara County FC&WCD", "Delivery - IN"],
    ["SWP_IN_SCV", "Santa Clara Valley WD", "Delivery - IN"],
    ["SWP_IN_SOLANO", "Solano County WA", "Delivery - IN"],
    ["SWP_IN_TULARE", "Tulare Lake Basin WSD", "Delivery - IN"],
    ["SWP_IN_VC", "Ventura County FCD", "Delivery - IN"],
    ["SWP_IN_CLWA1", "Santa Clarita WA (San Joaquin)", "Delivery - IN"],
]

a_sv_list = [
    ["I_ALD002", "Alder Creek (below Alder Creek Diversion Dam)", "SV - Inflow"],
    [
        "I_ALD004",
        "Alder Creek (at Proposed Site of Alder Creek Reservoir)",
        "SV - Inflow",
    ],
    ["I_ALMNR", "Inflow to Lake Almanor", "SV - Inflow"],
    ["I_ALOHA", "Pyramid Creek inflow to Lake Aloha", "SV - Inflow"],
    ["I_ANT011", "Antelope Creek", "SV - Inflow"],
    ["I_ANTLP", "Inflow to  Antelope Lake", "SV - Inflow"],
    ["I_BCC014", "Big Chico Creek", "SV - Inflow"],
    ["I_BCN010", "Bear Creek (Tributary to Sacramento River)", "SV - Inflow"],
    ["I_BLKBT", "Local inflow to Black Butte Resrvoir", "SV - Inflow"],
    ["I_BOWMN", "Local inflow to Bowman Lake", "SV - Inflow"],
    ["I_BRC003", "Local inflows to Cache Creek from Bear Creek", "SV - Inflow"],
    ["I_BRR023", "Local inflow to Garden Bar Dam Site", "SV - Inflow"],
    ["I_PTH070", "Inflow to Lake Berryessa", "SV - Inflow"],
    ["I_BSH003", "Brush Creek inflow to Brush Creek Reservoir", "SV - Inflow"],
    ["I_BTC048", "Butte Creek inflow to Battle Creek", "SV - Inflow"],
    ["I_BTL006", "Battle Creek", "SV - Inflow"],
    ["I_BTVLY", "Inflow to Butt Valley Reservoir", "SV - Inflow"],
    ["I_BUCKS", "Bucks Creek inflow to Lower Bucks Creek Reservoir", "SV - Inflow"],
    ["I_CAPLS", "Inflow to Caples Lake", "SV - Inflow"],
    ["I_CCH053", "Local inflows to Cache Creek downstream of Rumsey", "SV - Inflow"],
    ["I_CLR011", "Local inflows to Clear Creek at Igo", "SV - Inflow"],
    ["I_CLRLK", "Cache Creek inflow to Clear Lake", "SV - Inflow"],
    ["I_CMBIE", "Local inflow to Combie Reservoir", "SV - Inflow"],
    ["I_CMPFW", "Local inflow to Camp Far West Reservoir", "SV - Inflow"],
    ["I_COW014", "Cow Creek", "SV - Inflow"],
    [
        "I_CWD018",
        "North and Middle Forks Cottonwood Creek (Near Olinda)",
        "SV - Inflow",
    ],
    ["I_CYN009", "Inflow to Canyon Creek at Towle Canal Diversion Dam", "SV - Inflow"],
    ["I_DAVIS", "Inflow to Davis Lake", "SV - Inflow"],
    ["I_DCC010", "Duncan Canyon Creek", "SV - Inflow"],
    ["I_DER001", "Local inflow to Deer Creek near Smartville", "SV - Inflow"],
    ["I_DER004", "Local inflow to Deer Creek at Lake Wildwood", "SV - Inflow"],
    ["I_DHC021", "Dry Creek and Hutchinson Creek", "SV - Inflow"],
    ["I_DRC012", "Deer Creek near Vina", "SV - Inflow"],
    [
        "I_EBF001",
        "Local inflow to East Branch NF Feather River below Antelope Lake",
        "SV - Inflow",
    ],
    ["I_ECHOL", "Echo Lake", "SV - Inflow"],
    ["I_ELD027", "Elder Creek", "SV - Inflow"],
    ["I_ENGLB", "Local inflow to Englebright Reservoir", "SV - Inflow"],
    ["I_EPARK", "Stony Creek inflow to East Park Dam", "SV - Inflow"],
    ["I_FOLSM", "Local inflow to Folsom Lake", "SV - Inflow"],
    ["I_FRDYC", "Inflow to Fordyce Lake", "SV - Inflow"],
    ["I_FRMAN", "Frenchman Lake inflows", "SV - Inflow"],
    ["I_FRMDW", "Inflow to French Meadows Reservoir", "SV - Inflow"],
    ["I_FRNCH", "Inflow to French Lake", "SV - Inflow"],
    ["I_GERLE", "Local inflow to Gerle Reservoir", "SV - Inflow"],
    [
        "I_GZL009",
        "Local inflow to Grizzly Creek upstream of Grizzly Forebay",
        "SV - Inflow",
    ],
    ["I_HHOLE", "Local inflow to Hell Hole Reservoir", "SV - Inflow"],
    ["I_HON021", "Honcut Creek", "SV - Inflow"],
    ["I_ICEHS", "Inflow to Ice House Reservoir", "SV - Inflow"],
    ["I_INDVL", "NF Cache Creek inflow to Indian Valley Reservoir", "SV - Inflow"],
    ["I_JKSMD", "Inflow to Jackson Meadows", "SV - Inflow"],
    ["I_LCBRF", "Texas, Fall, and Rucker Creeks", "SV - Inflow"],
    ["I_LCC038", "Little Chico Creek", "SV - Inflow"],
    ["I_LDC029", "Little Dry Creek", "SV - Inflow"],
    ["I_LGRSV", "South Fork Feather River", "SV - Inflow"],
    ["I_LKVLY", "Inflow to Lake Valley Reservoir (NF American River)", "SV - Inflow"],
    ["I_LNG012", "Local inflow to Long Canyon Creek", "SV - Inflow"],
    ["I_LOONL", "Inflow to Loon Lake", "SV - Inflow"],
    ["I_LRB004", "Little Rubicon River inflow to Buck Island Lake", "SV - Inflow"],
    ["I_LWSTN", "Local inflow to Lewiston Reservoir", "SV - Inflow"],
    ["I_MERLC", "French Dry Creek inflow to Merle Collins Lake", "SV - Inflow"],
    [
        "I_MFA001",
        "Local inflow to Middle Fork American River near Auburn",
        "SV - Inflow",
    ],
    [
        "I_MFA023",
        "Local inflow to Middle Fork American River near Foresthill",
        "SV - Inflow",
    ],
    ["I_MFA025", "Local inflow to Middle Fork American River", "SV - Inflow"],
    [
        "I_MFA036",
        "Local inflow to Middle Fork American River at Interbay Dam",
        "SV - Inflow",
    ],
    [
        "I_MFF019",
        "Local inflow to Middle Fork Feather River near Merrimac",
        "SV - Inflow",
    ],
    [
        "I_MFF087",
        "Local inflow to Middle Fork Feather River near Portola",
        "SV - Inflow",
    ],
    ["I_MFY013", "Local inflow to MF Yuba River", "SV - Inflow"],
    ["I_MLC006", "Mill Creek", "SV - Inflow"],
    [
        "I_MNS000",
        "Inflows from Minor North-East Streams to Sacramento River",
        "SV - Inflow",
    ],
    ["I_MTMDW", "Inflow to Mountain Meadows Reservoir", "SV - Inflow"],
    ["I_NBLDB", "Local inflow to New Bullards Bar Reservoir", "SV - Inflow"],
    [
        "I_NFA016",
        "Local inflow to NF American River at Auburn Tunnel Pump Station Diversion",
        "SV - Inflow",
    ],
    ["I_NFA022", "Local inflow to NF American River at North Fork Dam", "SV - Inflow"],
    ["I_NFA054", "North Fork American River", "SV - Inflow"],
    ["I_NFF029", "Local inflow to NF Feather River above Poe Dam", "SV - Inflow"],
    ["I_NFY029", "North Fork Yuba River and local inflows", "SV - Inflow"],
    ["I_NLC003", "North Fork of Long Canyon Creek", "SV - Inflow"],
    ["I_NMA003", "North Fork of Middle Fork American River", "SV - Inflow"],
    ["I_NNA013", "Local inflow to NF American River", "SV - Inflow"],
    ["I_OGN005", "Oregon Creek", "SV - Inflow"],
    ["I_OROVL", "Local inflow to Lake Oroville", "SV - Inflow"],
    ["I_PLC007", "Local inflow to Pilot Creek downstream of Georgetown", "SV - Inflow"],
    ["I_PLM001", "Plum Creek", "SV - Inflow"],
    ["I_PYN001", "Paynes and Sevenmile creeks", "SV - Inflow"],
    ["I_PYR001", "Local inflow to Pyramid Creek at Twin Bridges", "SV - Inflow"],
    ["I_RCK001", "Rock Creek", "SV - Inflow"],
    ["I_RLLNS", "Local inflow to Rollins Reservoir", "SV - Inflow"],
    ["I_RUB002", "Local inflow to Rubicon River near Foresthill", "SV - Inflow"],
    ["I_RUB047", "Inflow to Rubicon Reservoir", "SV - Inflow"],
    ["I_RVPHB", "Inflow to Round Valley and Philbrook Reservoirs", "SV - Inflow"],
    ["I_SCOTF", "Local inflow to Scotts Flat", "SV - Inflow"],
    ["I_SCW008", "South Fork Cottonwood Creek", "SV - Inflow"],
    [
        "I_SFA030",
        "Local inflow to South Fork American River near Placerville",
        "SV - Inflow",
    ],
    [
        "I_SFA040",
        "Slab Creek inflow to South Fork American River at Slab Creek Reservoir",
        "SV - Inflow",
    ],
    [
        "I_SFA066",
        "Local inflow to South Fork American River near Kyburz",
        "SV - Inflow",
    ],
    [
        "I_SFA076",
        "Local inflow to South Fork American River near Forni Creek",
        "SV - Inflow",
    ],
    [
        "I_SFD003",
        "Inflow to South Fork of Deer Creek downstream Deer Crk Powerhouse",
        "SV - Inflow",
    ],
    [
        "I_SFF008",
        "Local inflow to South Fork Feather River at Enterprise",
        "SV - Inflow",
    ],
    [
        "I_SFF011",
        "Local inflow to South Fork Feather River at Ponderosa Reservoir",
        "SV - Inflow",
    ],
    ["I_SFR006", "South Fork Rubicon River", "SV - Inflow"],
    ["I_SFY007", "Local inflow to SF Yuba River", "SV - Inflow"],
    ["I_SFY048", "South Fork Yuba River Near Cisco", "SV - Inflow"],
    ["I_SGRGE", "Local inflow to Stony Gorge Reservoir", "SV - Inflow"],
    ["I_SHSTA", "Inflow to Shasta Lake", "SV - Inflow"],
    ["I_SILVR", "Inflow to Silver Lake", "SV - Inflow"],
    ["I_SLC003", "South Fork Long Canyon Creek", "SV - Inflow"],
    [
        "I_SLF009",
        "Local inflow to Silver Fork American River at Proposed Diversion for Alder Creek Reservoir",
        "SV - Inflow",
    ],
    ["I_SLT009", "Slate Creek", "SV - Inflow"],
    ["I_SLV006", "Local inflow to Silver Creek at Camino Reservoir", "SV - Inflow"],
    ["I_SLV015", "Local inflow to Silver Creek at Junction Reservoir", "SV - Inflow"],
    ["I_SLYCK", "Sly Creek", "SV - Inflow"],
    ["I_SPLDG", "Local inflow to Spaulding Reservoir", "SV - Inflow"],
    ["I_STMPY", "Inflow to Stumpy Meadows Reservoir", "SV - Inflow"],
    ["I_THM028", "Thomes Creek", "SV - Inflow"],
    ["I_TRNTY", "Inflow to Claire Engle (Trinity) Lake", "SV - Inflow"],
    ["I_UNVLY", "Inflow to Union Valley Reservoir", "SV - Inflow"],
    ["I_WBF006", "Local inflow to WB Feather River at Yankee Hill", "SV - Inflow"],
    [
        "I_WBF015",
        "Local inflow to WB Feather River at Miocene Diversion Dam",
        "SV - Inflow",
    ],
    ["I_WBF030", "West Branch Feather River", "SV - Inflow"],
    ["I_WBR001", "Weber Creek", "SV - Inflow"],
    ["I_WKYTN", "Clear Creek inflow to Whiskeytown Lake", "SV - Inflow"],
    ["I_WLF013", "Wolf Creek", "SV - Inflow"],
    ["I_AMADR", "Jackson Creek inflow to Jackson Reservoir", "SV - Inflow"],
    ["I_ANG017", "Angel Creek inflows to Murphys Afterbay", "SV - Inflow"],
    ["I_BANOS", "Los Banos Creek inflows to Los Banos Reservoir", "SV - Inflow"],
    ["I_BCK040", "Bear Creek inflows to Bear Reservoir (Merced County)", "SV - Inflow"],
    ["I_BEARD", "Inflow to Beardsley Lake", "SV - Inflow"],
    ["I_BUR005", "Burns Creek", "SV - Inflow"],
    [
        "I_BVC007",
        "Beaver Creek inflows upstream of Beaver Creek Diversion Dam",
        "SV - Inflow",
    ],
    ["I_CAP000", "Capita Canyon and minor streams", "SV - Inflow"],
    [
        "I_CFS001",
        "Clark Fork Stanislaus River inflows to Middle Fork Stanislaus",
        "SV - Inflow",
    ],
    ["I_CHC000", "Corral Hollow and minor creeks", "SV - Inflow"],
    ["I_CHW031", "Local inflow to Chowchilla River below Buchanan Dam", "SV - Inflow"],
    ["I_CLV026", "Local inflow to Calaveras River at Bellota Weir", "SV - Inflow"],
    ["I_CMCHE", "Local inflow to Camanche Reservoir", "SV - Inflow"],
    [
        "I_CMP001",
        "Local inflows Camp Creek below Sly Park Creek Confluence",
        "SV - Inflow",
    ],
    ["I_CMP014", "Camp Creek", "SV - Inflow"],
    ["I_COL003", "Cole Creek", "SV - Inflow"],
    ["I_COT033", "Cottonwood Creek", "SV - Inflow"],
    ["I_CSM035", "Cosumnes River", "SV - Inflow"],
    ["I_DBC024", "Dry Creek and Berenda Creek", "SV - Inflow"],
    ["I_DCM027", "Dry Creek (Merced)", "SV - Inflow"],
    ["I_DCT050", "Dry Creek (Tuolumne)", "SV - Inflow"],
    ["I_DED044", "Deadman and Dutchman Creeks", "SV - Inflow"],
    ["I_DEE023", "Dear Creek (inflow to Consumnes)", "SV - Inflow"],
    ["I_DONLL", "Inflow to Donnells Lake", "SV - Inflow"],
    ["I_DPC008", "Del Puerto Creek", "SV - Inflow"],
    ["I_DSC035", "Dry Creek and Secret Creek", "SV - Inflow"],
    ["I_ELENR", "Inflow to Lake Eleanor", "SV - Inflow"],
    ["I_ESTMN", "Chowchilla River inflows to Eastman Lake", "SV - Inflow"],
    [
        "I_FRS046",
        "Local inflow to Fresno River below Hidden Dam near Daulton",
        "SV - Inflow",
    ],
    ["I_FSL012", "Fresno Slough", "SV - Inflow"],
    ["I_GRZ012", "Garzas Creek", "SV - Inflow"],
    ["I_HNSLY", "Fresno River inflows to Hensley Lake", "SV - Inflow"],
    ["I_HTCHY", "Inflow To Hetch Hetchy Reservoir", "SV - Inflow"],
    ["I_ING008", "Hospital and Ingram Creeks", "SV - Inflow"],
    ["I_JBP006", "James Bypass", "SV - Inflow"],
    [
        "I_JNKSN",
        "Sly Park Creek and Hazel Creek inflow to Jenkinson Lake",
        "SV - Inflow",
    ],
    ["I_LJC022", "Littlejohns Creek", "SV - Inflow"],
    ["I_LLOYD", "Inflow to Lake Lloyd/Cherry Lake", "SV - Inflow"],
    ["I_LOSVQ", "Kellogg Creek Inflow to Los Vaqueros Reservoir", "SV - Inflow"],
    ["I_LPC007", "Little Panoche Creek", "SV - Inflow"],
    ["I_LYONS", "Inflow to Lyons Reservoir", "SV - Inflow"],
    [
        "I_MCD055",
        "Local inflow to Merced River at Merced Falls Diversion Dam",
        "SV - Inflow",
    ],
    ["I_MCLRE", "Local inflow to Lake McClure", "SV - Inflow"],
    ["I_MFM008", "Middle Fork Mokelumne River", "SV - Inflow"],
    [
        "I_MFS013",
        "Local Inflow to MF Stanislaus River at Sand Bar Diversion Dam",
        "SV - Inflow",
    ],
    [
        "I_MFS022",
        "Local inflow to MF Stanislaus River above Hells Half Acre Bridge",
        "SV - Inflow",
    ],
    ["I_MFS047", "Kennedy Creek Inflow to MF Stanislaus River", "SV - Inflow"],
    ["I_MIL003", "Mills Creek", "SV - Inflow"],
    ["I_MLRTN", "San Joaquin River inflows to Millerton Reservoir", "SV - Inflow"],
    [
        "I_MOK079",
        "Local Inflow to Mokelumne River above Pardee Reservoir",
        "SV - Inflow",
    ],
    ["I_MPS038", "Mariposa Creek", "SV - Inflow"],
    ["I_MSH015", "Marsh Creek inflows to the Delta", "SV - Inflow"],
    ["I_NFM010", "Local Inflow to NF Mokelumne River", "SV - Inflow"],
    [
        "I_NFS005",
        "Local inflow to NF Stanislaus River below Beaver Creek",
        "SV - Inflow",
    ],
    ["I_NFS009", "Local inflow to NF Stanislaus River near Avery", "SV - Inflow"],
    ["I_NFS033", "North Fork Stanislaus River", "SV - Inflow"],
    ["I_NHGAN", "Calaveras River inflows to New Hogan Dam", "SV - Inflow"],
    ["I_ORG000", "Ortigalita Creek", "SV - Inflow"],
    ["I_ORT014", "Orestimba Creek", "SV - Inflow"],
    ["I_OWN040", "Owens Creek", "SV - Inflow"],
    ["I_PARDE", "Local Inflow to Pardee Reservoir", "SV - Inflow"],
    ["I_PCRST", "Inflow to Pinecrest Lake", "SV - Inflow"],
    ["I_PEDRO", "Tuolumne River inflows to New Don Pedro Dam", "SV - Inflow"],
    ["I_QNT005", "Quinto Creek", "SV - Inflow"],
    ["I_RLIEF", "Relief Creek", "SV - Inflow"],
    ["I_SFM005", "South Fork Mokelumne River", "SV - Inflow"],
    ["I_SFS030", "Local inflow to SF Stanislaus River", "SV - Inflow"],
    [
        "I_SFS033",
        "Local inflow to South Fork Stanislaus River above Strawberry",
        "SV - Inflow",
    ],
    [
        "I_SJR258",
        "Local inflow from Little Dry Creek to San Joaquin River",
        "SV - Inflow",
    ],
    [
        "I_SJR265",
        "Local inflow from Cottonwood Creek to San Joaquin River",
        "SV - Inflow",
    ],
    ["I_SLO007", "Salado Creek", "SV - Inflow"],
    ["I_SLTSP", "Inflow to Salt Springs Reservoir", "SV - Inflow"],
    ["I_SLUIS", "Local inflows to San Luis Reservoir", "SV - Inflow"],
    ["I_SPICE", "Highland Creek", "SV - Inflow"],
    [
        "I_STS059",
        "Local inflow to Stanislaus River below Tulloch Reservoir",
        "SV - Inflow",
    ],
    ["I_STS072", "Local inflow to New Melones Reservoir", "SV - Inflow"],
    ["I_TGC003", "Tiger Creek", "SV - Inflow"],
    ["I_TULOC", "Local inflow to Tullock Reservoir", "SV - Inflow"],
    ["I_TUO054", "Local inflow to Tuolumne River at LaGrange Dam", "SV - Inflow"],
    ["I_UBEAR", "Inflow to Upper Bear River Reservoir", "SV - Inflow"],
]


def generate_yaml_file(varlist, filename):
    """
    Generate a YAML file with given data.

    Args:
    - data: Dictionary containing the data to be written to the YAML file.
    - filename: Name of the YAML file to be generated.
    """
    data = {}

    for var in varlist:
        data[var[0]] = {
            "bpart": var[0],
            "pathname": f"/CALSIM/{var[0]}/.*//.*/.*/",
            "alias": var[1],
            "table_convert": "cfs_taf",
            "table_display": "wy",
            "type": var[2],
        }

    with open(filename, "w") as file:
        yaml.dump(data, file)
    print(f"YAML file '{filename}' generated successfully.")


generate_yaml_file(a_sv_list, "sv_inflows.yaml")
